set(_CATKIN_CURRENT_PACKAGE "youbot_arm_server")
set(youbot_arm_server_VERSION "0.0.0")
set(youbot_arm_server_MAINTAINER "staubli-tx-40 <staubli-tx-40@todo.todo>")
set(youbot_arm_server_PACKAGE_FORMAT "1")
set(youbot_arm_server_BUILD_DEPENDS "geometry_msgs" "roscpp" "tf" "moveit_core" "moveit_ros_planning_interface" "tf_conversions" "actionlib_msgs" "std_msgs" "control_msgs")
set(youbot_arm_server_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "tf" "moveit_core" "moveit_ros_planning_interface" "tf_conversions" "actionlib_msgs" "std_msgs" "control_msgs")
set(youbot_arm_server_BUILDTOOL_DEPENDS "catkin")
set(youbot_arm_server_BUILDTOOL_EXPORT_DEPENDS )
set(youbot_arm_server_EXEC_DEPENDS "geometry_msgs" "roscpp" "tf" "moveit_core" "moveit_ros_planning_interface" "tf_conversions" "actionlib_msgs" "std_msgs" "control_msgs")
set(youbot_arm_server_RUN_DEPENDS "geometry_msgs" "roscpp" "tf" "moveit_core" "moveit_ros_planning_interface" "tf_conversions" "actionlib_msgs" "std_msgs" "control_msgs")
set(youbot_arm_server_TEST_DEPENDS )
set(youbot_arm_server_DOC_DEPENDS )
set(youbot_arm_server_DEPRECATED "")